# Generated by Django 3.1.4 on 2021-02-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210102_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_email', models.CharField(max_length=256)),
                ('send_date', models.DateTimeField()),
                ('subject', models.CharField(max_length=256)),
            ],
        ),
    ]
