# Generated by Django 3.1.4 on 2021-02-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_email', models.CharField(max_length=256)),
                ('send_date', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Emails',
        ),
    ]
