# Generated by Django 3.1.4 on 2021-02-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210219_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
